services:

  db_postgres:
    container_name: my_postgres
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"

    volumes:
      - ./db/:/var/lib/postgresql/data
  bot:
    container_name: valog_bot
    build: .

    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db_postgres:5432/my_db

    ports:
      - "8080:8080"

    depends_on:
      - db_postgres
